apiVersion: apps/v1
kind: Deployment
metadata:
  name: dnetc
  labels:
    app: dnetc
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dnetc
  template:
    metadata:
      labels:
        app: dnetc
    spec:
      containers:
      - name: dnetc
        image: recklessop/dnetc-client:latest
        imagePullPolicy: Always
